pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'xa-mass-platform'

include ':foundation_jvm'
include ':kernel_jvm'
include ':server_jvm'
include ':worker_delivery_contract_jvm'
include ':transport:netty-adapter'
include ':transport:okhttp-worker'
