xa:
  mass:
    worker-delivery:
      adapter:
        instances:
          websocket-1:
            type: WEBSOCKET
            listen-host: 127.0.0.1
            listen-port: 18083
    worker-assembly:
      bundles:
        phone-number:
          type: PHONE_NUMBER
          adapter-id: websocket-1
          worker-group-id: phonenumber-workers
          worker-id-prefix: phonenumber-worker-
