xa:
  mass:
    worker-delivery:
      adapter:
        instances:
          scenario-websocket:
            type: WEBSOCKET
            listen-host: 127.0.0.1
            listen-port: 18083
    worker-binding:
      endpoints:
        scenario-websocket:
          transport-type: WEBSOCKET
          public-uri: ws://127.0.0.1:18083/api/v1/worker-delivery/websocket
    worker-assembly:
      runtime-api-base-url: http://127.0.0.1:18082
      sandbox-root: data/scenario-workers
      group-config-json: |
        {
          "scenario-phone-number-workers": {
            "attributes": {"capability":"libphonenumber"},
            "eventCodes": [
              "phonenumber.e164",
              "phonenumber.country",
              "phonenumber.original-carrier"
            ]
          },
          "scenario-string-utils-workers": {
            "attributes": {"capability":"string-utils"},
            "eventCodes": [
              "string.md5",
              "string.sha1",
              "string.base64.encode"
            ]
          }
        }
      worker-config-json: |
        {
          "scenario-phone-number-workers": {
            "eventCodes": [
              "phonenumber.e164",
              "phonenumber.country",
              "phonenumber.original-carrier"
            ]
          },
          "scenario-string-utils-workers": {
            "eventCodes": [
              "string.md5",
              "string.sha1",
              "string.base64.encode"
            ]
          }
        }
