xa:
  mass:
    worker-delivery:
      adapter:
        instances:
          scenario-websocket:
            type: WEBSOCKET
            listen-host: 127.0.0.1
            listen-port: 18083
    worker-binding:
      endpoints:
        scenario-websocket:
          transport-type: WEBSOCKET
          public-uri: ws://127.0.0.1:18083/api/v1/worker-delivery/websocket
    worker-assembly:
      runtime-api-base-url: http://127.0.0.1:18082
      group-config-json: |
        {
          "scenario-phone-number-workers": {
            "attributes": {"capability":"libphonenumber"},
            "eventCodes": [
              "phonenumber.e164",
              "phonenumber.country",
              "phonenumber.original-carrier"
            ]
          },
          "scenario-string-utils-workers": {
            "attributes": {"capability":"string-utils"},
            "eventCodes": [
              "string.md5",
              "string.sha1",
              "string.base64.encode"
            ]
          }
        }
      worker-config-json: |
        {
          "scenario-phone-number-workers": {
            "eventCodes": [
              "phonenumber.e164",
              "phonenumber.country",
              "phonenumber.original-carrier"
            ],
            "workers": [
              {"clientWorkerKey":"scenario-phone-number-worker-001","sandboxDirectory":"data/scenario-workers/scenario-phone-number-worker-001","workerProperties":{"runtime":"java","capability":"libphonenumber","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-phone-number-worker-002","workerProperties":{"runtime":"java","capability":"libphonenumber","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-phone-number-worker-003","workerProperties":{"runtime":"java","capability":"libphonenumber","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-phone-number-worker-004","workerProperties":{"runtime":"java","capability":"libphonenumber","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-phone-number-worker-005","workerProperties":{"runtime":"java","capability":"libphonenumber","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-phone-number-worker-006","workerProperties":{"runtime":"java","capability":"libphonenumber","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-phone-number-worker-007","workerProperties":{"runtime":"java","capability":"libphonenumber","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-phone-number-worker-008","workerProperties":{"runtime":"java","capability":"libphonenumber","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-phone-number-worker-009","workerProperties":{"runtime":"java","capability":"libphonenumber","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-phone-number-worker-010","workerProperties":{"runtime":"java","capability":"libphonenumber","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}}
            ]
          },
          "scenario-string-utils-workers": {
            "eventCodes": [
              "string.md5",
              "string.sha1",
              "string.base64.encode"
            ],
            "workers": [
              {"clientWorkerKey":"scenario-string-utils-worker-001","sandboxDirectory":"data/scenario-workers/scenario-string-utils-worker-001","workerProperties":{"runtime":"java","capability":"string-utils","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-string-utils-worker-002","workerProperties":{"runtime":"java","capability":"string-utils","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-string-utils-worker-003","workerProperties":{"runtime":"java","capability":"string-utils","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-string-utils-worker-004","workerProperties":{"runtime":"java","capability":"string-utils","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-string-utils-worker-005","workerProperties":{"runtime":"java","capability":"string-utils","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-string-utils-worker-006","workerProperties":{"runtime":"java","capability":"string-utils","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-string-utils-worker-007","workerProperties":{"runtime":"java","capability":"string-utils","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-string-utils-worker-008","workerProperties":{"runtime":"java","capability":"string-utils","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-string-utils-worker-009","workerProperties":{"runtime":"java","capability":"string-utils","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}},
              {"clientWorkerKey":"scenario-string-utils-worker-010","workerProperties":{"runtime":"java","capability":"string-utils","region":"local"},"indexedPropertyUpdates":{"index.worker.region":"local"}}
            ]
          }
        }
