 xa:
  mass:
    worker-delivery:
      adapter:
        instances:
          android-demo-websocket:
            type: WEBSOCKET
            listen-host: 127.0.0.1
            listen-port: 18085
    worker-binding:
      endpoints:
        android-demo-websocket:
          transport-type: WEBSOCKET
          public-uri: ws://127.0.0.1:18085/api/v1/worker-delivery/websocket
    worker-assembly:
      runtime-api-base-url: http://127.0.0.1:18082
      group-config-json: |
        {
          "android-demo-workers": {
            "attributes": {
              "capability": "android-demo-state"
            },
            "eventCodes": [
              "android.demo.state.read"
            ]
          }
        }
      worker-config-json: '{}'
