import org.springframework.boot.gradle.plugin.SpringBootPlugin

plugins {
    id 'java-library'
    id 'org.springframework.boot'
}

base {
    archivesName.set('xa-mass-worker-delivery-adapter-jvm')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

springBoot {
    mainClass = 'com.xa.mass.workerdelivery.adapter.standalone.WorkerDeliveryAdapterApplication'
}

dependencies {
    implementation platform(SpringBootPlugin.BOM_COORDINATES)
    implementation platform('tools.jackson:jackson-bom:3.1.4')
    annotationProcessor platform(SpringBootPlugin.BOM_COORDINATES)
    testImplementation platform(SpringBootPlugin.BOM_COORDINATES)

    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'tools.jackson.core:jackson-databind'
    implementation project(':worker_delivery_contract_jvm')

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('jar') {
    enabled = true
}

tasks.named('test') {
    useJUnitPlatform()
}
