spring.application.name=mass_mock
server.port=8089

# WebSocket server configuration
websocket.server.uri=ws://localhost:8088/ws

# Mock client configuration
mock.client.count=5
mock.task.interval=30000 