CREATE TABLE IF NOT EXISTS xa_task (
  task_id VARCHAR(128) PRIMARY KEY,
  status VARCHAR(64),
  project VARCHAR(128),
  schedulable BOOLEAN,
  max_runtime_deadline TIMESTAMP,
  json TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_xa_task_status ON xa_task(status);
CREATE INDEX IF NOT EXISTS idx_xa_task_project ON xa_task(project);
CREATE INDEX IF NOT EXISTS idx_xa_task_deadline ON xa_task(max_runtime_deadline);

CREATE TABLE IF NOT EXISTS xa_task_msg (
  task_id VARCHAR(128) NOT NULL,
  message_id VARCHAR(128) NOT NULL,
  status VARCHAR(64),
  final_state BOOLEAN,
  json TEXT NOT NULL,
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY(task_id, message_id)
);

CREATE INDEX IF NOT EXISTS idx_xa_task_msg_task_seq ON xa_task_msg(task_id, seq);
CREATE INDEX IF NOT EXISTS idx_xa_task_msg_task_final ON xa_task_msg(task_id, final_state);

CREATE TABLE IF NOT EXISTS xa_task_msg_attempt (
  task_id VARCHAR(128) NOT NULL,
  message_id VARCHAR(128) NOT NULL,
  attempt_id VARCHAR(128) NOT NULL,
  status VARCHAR(64),
  active_state BOOLEAN,
  json TEXT NOT NULL,
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY(task_id, message_id, attempt_id)
);

CREATE INDEX IF NOT EXISTS idx_xa_attempt_msg_seq ON xa_task_msg_attempt(task_id, message_id, seq);
CREATE INDEX IF NOT EXISTS idx_xa_attempt_task_status ON xa_task_msg_attempt(task_id, status);

CREATE TABLE IF NOT EXISTS xa_worker (
  worker_id VARCHAR(128) PRIMARY KEY,
  worker_group_id VARCHAR(128),
  json TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_xa_worker_group ON xa_worker(worker_group_id);

CREATE TABLE IF NOT EXISTS xa_worker_context (
  worker_context_id VARCHAR(128) PRIMARY KEY,
  worker_id VARCHAR(128) NOT NULL,
  json TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_xa_worker_context_worker ON xa_worker_context(worker_id);

CREATE TABLE IF NOT EXISTS xa_worker_lock (
  worker_id VARCHAR(128) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS xa_rule (
  rule_id VARCHAR(128) PRIMARY KEY,
  rule_type VARCHAR(64),
  json TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_xa_rule_type ON xa_rule(rule_type);
