package com.xa.mass.server.storage;

import com.xa.mass.base.enums.task.TaskStatus;
import com.xa.mass.base.enums.taskmsg.TaskMsgAttemptStatus;
import com.xa.mass.base.enums.taskmsg.TaskMsgStatus;
import com.xa.mass.base.model.Task;
import com.xa.mass.base.model.TaskMsg;
import com.xa.mass.base.model.TaskMsgAttempt;
import com.xa.mass.engine.storage.TaskStorage;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Server-owned H2 adapter for local and CI persistence verification.
 *
 * <p>Status columns on message and attempt tables are bounded per-task runtime
 * indexes for convergence and cleanup. Do not expand this adapter into a
 * cross-task message analytics surface; high-volume detail belongs in trace or
 * audit sinks.</p>
 */
public class H2TaskStorage extends JdbcStorageSupport implements TaskStorage {

    public H2TaskStorage(String jdbcUrl, String username, String password) {
        super(jdbcUrl, username, password);
        initialize();
    }

    private void initialize() {
        try (var conn = connection(); var stmt = conn.createStatement()) {
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS xa_task (
                      task_id VARCHAR(128) PRIMARY KEY,
                      status VARCHAR(64),
                      project VARCHAR(128),
                      schedulable BOOLEAN,
                      max_runtime_deadline TIMESTAMP,
                      json CLOB NOT NULL
                    )
                    """);
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_xa_task_status ON xa_task(status)");
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_xa_task_project ON xa_task(project)");
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_xa_task_deadline ON xa_task(max_runtime_deadline)");
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS xa_task_msg (
                      task_id VARCHAR(128) NOT NULL,
                      message_id VARCHAR(128) NOT NULL,
                      status VARCHAR(64),
                      final_state BOOLEAN,
                      json CLOB NOT NULL,
                      seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      PRIMARY KEY(task_id, message_id)
                    )
                    """);
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_xa_task_msg_task_seq ON xa_task_msg(task_id, seq)");
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_xa_task_msg_task_final ON xa_task_msg(task_id, final_state)");
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS xa_task_msg_attempt (
                      task_id VARCHAR(128) NOT NULL,
                      message_id VARCHAR(128) NOT NULL,
                      attempt_id VARCHAR(128) NOT NULL,
                      status VARCHAR(64),
                      active_state BOOLEAN,
                      json CLOB NOT NULL,
                      seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      PRIMARY KEY(task_id, message_id, attempt_id)
                    )
                    """);
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_xa_attempt_msg_seq ON xa_task_msg_attempt(task_id, message_id, seq)");
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_xa_attempt_task_status ON xa_task_msg_attempt(task_id, status)");
        } catch (Exception e) {
            throw new IllegalStateException("Failed to initialize H2 task storage", e);
        }
    }

    @Override
    public synchronized void saveTask(Task task) {
        if (task == null || task.getTid() == null) {
            throw new IllegalArgumentException("task and task id are required");
        }
        try (var conn = connection()) {
            try (var ps = conn.prepareStatement("""
                    MERGE INTO xa_task KEY(task_id)
                    VALUES (?, ?, ?, ?, ?, ?)
                    """)) {
                bindTask(ps, task);
                ps.executeUpdate();
            }
        } catch (Exception e) {
            throw new IllegalStateException("Failed to save task " + task.getTid(), e);
        }
    }

    @Override
    public Optional<Task> getTask(String taskId) {
        return queryOneTask("SELECT json FROM xa_task WHERE task_id = ?", taskId);
    }

    @Override
    public synchronized boolean updateTask(Task task) {
        if (task == null || task.getTid() == null) {
            return false;
        }
        try (var conn = connection(); var ps = conn.prepareStatement("""
                UPDATE xa_task SET status = ?, project = ?, schedulable = ?, max_runtime_deadline = ?, json = ?
                WHERE task_id = ?
                """)) {
            ps.setString(1, task.getStatus() == null ? null : task.getStatus().name());
            ps.setString(2, task.getProject());
            ps.setBoolean(3, task.isSchedulable());
            setTimestamp(ps, 4, maxRuntimeDeadline(task));
            ps.setString(5, json(task));
            ps.setString(6, task.getTid());
            return ps.executeUpdate() > 0;
        } catch (Exception e) {
            throw new IllegalStateException("Failed to update task " + task.getTid(), e);
        }
    }

    @Override
    public synchronized boolean deleteTask(String taskId) {
        try (var conn = connection()) {
            conn.setAutoCommit(false);
            try {
                executeUpdate(conn, "DELETE FROM xa_task_msg_attempt WHERE task_id = ?", taskId);
                executeUpdate(conn, "DELETE FROM xa_task_msg WHERE task_id = ?", taskId);
                int deleted = executeUpdate(conn, "DELETE FROM xa_task WHERE task_id = ?", taskId);
                conn.commit();
                return deleted > 0;
            } catch (Exception e) {
                conn.rollback();
                throw e;
            }
        } catch (Exception e) {
            throw new IllegalStateException("Failed to delete task " + taskId, e);
        }
    }

    @Override
    public List<Task> getAllTasks() {
        return queryTasks("SELECT json FROM xa_task");
    }

    @Override
    public List<Task> getTasksByStatus(TaskStatus status) {
        return queryTasks("SELECT json FROM xa_task WHERE status = ?", status == null ? null : status.name());
    }

    @Override
    public List<Task> getTasksByProject(String project) {
        return queryTasks("SELECT json FROM xa_task WHERE project = ?", project);
    }

    @Override
    public List<Task> getSchedulableTasks() {
        return queryTasks("SELECT json FROM xa_task WHERE schedulable = TRUE");
    }

    @Override
    public List<Task> pollExpiredMaxRuntimeTasks(LocalDateTime now, int limit) {
        if (now == null || limit <= 0) {
            return List.of();
        }
        try (var conn = connection(); var ps = conn.prepareStatement("""
                SELECT json FROM xa_task
                WHERE max_runtime_deadline IS NOT NULL AND max_runtime_deadline < ?
                ORDER BY max_runtime_deadline
                LIMIT ?
                """)) {
            ps.setTimestamp(1, Timestamp.valueOf(now));
            ps.setInt(2, limit);
            return readTasks(ps);
        } catch (Exception e) {
            throw new IllegalStateException("Failed to poll expired max-runtime tasks", e);
        }
    }

    @Override
    public synchronized void addTaskMessage(String taskId, TaskMsg taskMsg) {
        if (taskMsg == null || taskMsg.getMessageId() == null) {
            return;
        }
        try (var conn = connection(); var ps = conn.prepareStatement("""
                MERGE INTO xa_task_msg(task_id, message_id, status, final_state, json) KEY(task_id, message_id)
                VALUES (?, ?, ?, ?, ?)
                """)) {
            bindTaskMessage(ps, taskId, taskMsg);
            ps.executeUpdate();
        } catch (Exception e) {
            throw new IllegalStateException("Failed to save task message " + taskMsg.getMessageId(), e);
        }
    }

    @Override
    public List<TaskMsg> getTaskMessages(String taskId) {
        return queryMessages("SELECT json FROM xa_task_msg WHERE task_id = ? ORDER BY seq", taskId);
    }

    @Override
    public List<TaskMsg> getTaskMessages(String taskId, int limit) {
        if (limit <= 0) {
            return List.of();
        }
        return queryMessages("SELECT json FROM xa_task_msg WHERE task_id = ? ORDER BY seq LIMIT ?",
                taskId,
                String.valueOf(limit));
    }

    @Override
    public List<TaskMsg> getNonFinalTaskMessages(String taskId) {
        return queryMessages("SELECT json FROM xa_task_msg WHERE task_id = ? AND final_state = FALSE ORDER BY seq", taskId);
    }

    @Override
    public long countTaskMessages(String taskId) {
        return queryLong("SELECT COUNT(*) FROM xa_task_msg WHERE task_id = ?", taskId);
    }

    @Override
    public Optional<TaskMsg> getTaskMessage(String taskId, String messageId) {
        List<TaskMsg> messages = queryMessages("SELECT json FROM xa_task_msg WHERE task_id = ? AND message_id = ?", taskId, messageId);
        return messages.stream().findFirst();
    }

    @Override
    public synchronized boolean updateTaskMessage(String taskId, TaskMsg taskMsg) {
        if (taskMsg == null || taskMsg.getMessageId() == null) {
            return false;
        }
        try (var conn = connection(); var ps = conn.prepareStatement("""
                UPDATE xa_task_msg SET status = ?, final_state = ?, json = ?
                WHERE task_id = ? AND message_id = ?
                """)) {
            TaskMsgStatus status = taskMsg.getStatus();
            ps.setString(1, status == null ? null : status.name());
            ps.setBoolean(2, status == null || status.isFinal());
            ps.setString(3, json(taskMsg));
            ps.setString(4, taskId);
            ps.setString(5, taskMsg.getMessageId());
            return ps.executeUpdate() > 0;
        } catch (Exception e) {
            throw new IllegalStateException("Failed to update task message " + taskMsg.getMessageId(), e);
        }
    }

    @Override
    public synchronized void addTaskMessageAttempt(String taskId, String messageId, TaskMsgAttempt attempt) {
        if (attempt == null || attempt.getAttemptId() == null) {
            return;
        }
        try (var conn = connection(); var ps = conn.prepareStatement("""
                MERGE INTO xa_task_msg_attempt(task_id, message_id, attempt_id, status, active_state, json) KEY(task_id, message_id, attempt_id)
                VALUES (?, ?, ?, ?, ?, ?)
                """)) {
            bindAttempt(ps, taskId, messageId, attempt);
            ps.executeUpdate();
        } catch (Exception e) {
            throw new IllegalStateException("Failed to save task-message attempt " + attempt.getAttemptId(), e);
        }
    }

    @Override
    public List<TaskMsgAttempt> getTaskMessageAttempts(String taskId, String messageId) {
        return queryAttempts("SELECT json FROM xa_task_msg_attempt WHERE task_id = ? AND message_id = ? ORDER BY seq", taskId, messageId);
    }

    @Override
    public Optional<TaskMsgAttempt> getLatestTaskMessageAttempt(String taskId, String messageId) {
        return queryAttempts("SELECT json FROM xa_task_msg_attempt WHERE task_id = ? AND message_id = ? ORDER BY seq DESC LIMIT 1", taskId, messageId)
                .stream().findFirst();
    }

    @Override
    public Optional<TaskMsgAttempt> getLatestActiveTaskMessageAttempt(String taskId, String messageId) {
        return queryAttempts("SELECT json FROM xa_task_msg_attempt WHERE task_id = ? AND message_id = ? AND active_state = TRUE ORDER BY seq DESC LIMIT 1", taskId, messageId)
                .stream().findFirst();
    }

    @Override
    public TaskMessageAttemptStats getTaskMessageAttemptStats(String taskId, String messageId) {
        return attemptStats("WHERE task_id = ? AND message_id = ?", taskId, messageId);
    }

    @Override
    public synchronized boolean updateTaskMessageAttempt(String taskId, String messageId, TaskMsgAttempt attempt) {
        if (attempt == null || attempt.getAttemptId() == null) {
            return false;
        }
        try (var conn = connection(); var ps = conn.prepareStatement("""
                UPDATE xa_task_msg_attempt SET status = ?, active_state = ?, json = ?
                WHERE task_id = ? AND message_id = ? AND attempt_id = ?
                """)) {
            TaskMsgAttemptStatus status = attempt.getStatus();
            ps.setString(1, status == null ? null : status.name());
            ps.setBoolean(2, status != null && status.isActive());
            ps.setString(3, json(attempt));
            ps.setString(4, taskId);
            ps.setString(5, messageId);
            ps.setString(6, attempt.getAttemptId());
            return ps.executeUpdate() > 0;
        } catch (Exception e) {
            throw new IllegalStateException("Failed to update task-message attempt " + attempt.getAttemptId(), e);
        }
    }

    @Override
    public TaskMessageStats getTaskMessageStats(String taskId) {
        try (var conn = connection(); var ps = conn.prepareStatement("""
                SELECT COUNT(*) total,
                       SUM(CASE WHEN status = 'SUCCESS' THEN 1 ELSE 0 END) success_count,
                       SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END) failed_count,
                       SUM(CASE WHEN status = 'EXPIRED' THEN 1 ELSE 0 END) expired_count,
                       SUM(CASE WHEN status IN ('INIT','ASSIGNED','RUNNING','PENDING_RETRY') THEN 1 ELSE 0 END) processing_count
                FROM xa_task_msg WHERE task_id = ?
                """)) {
            ps.setString(1, taskId);
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) {
                    return new TaskMessageStats(0, 0, 0, 0, 0);
                }
                return new TaskMessageStats(rs.getLong(1), rs.getLong(2), rs.getLong(3), rs.getLong(4), rs.getLong(5));
            }
        } catch (Exception e) {
            throw new IllegalStateException("Failed to get task-message stats for task " + taskId, e);
        }
    }

    @Override
    public TaskMessageAttemptStats getTaskMessageAttemptStats(String taskId) {
        return attemptStats("WHERE task_id = ?", taskId);
    }

    private Optional<Task> queryOneTask(String sql, String arg) {
        List<Task> tasks = queryTasks(sql, arg);
        return tasks.stream().findFirst();
    }

    private List<Task> queryTasks(String sql, String... args) {
        try (var conn = connection(); var ps = conn.prepareStatement(sql)) {
            bindArgs(ps, args);
            return readTasks(ps);
        } catch (Exception e) {
            throw new IllegalStateException("Failed to query tasks", e);
        }
    }

    private List<Task> readTasks(PreparedStatement ps) throws Exception {
        List<Task> tasks = new ArrayList<>();
        try (ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                tasks.add(readJson(rs.getString(1), Task.class));
            }
        }
        return tasks;
    }

    private List<TaskMsg> queryMessages(String sql, String... args) {
        try (var conn = connection(); var ps = conn.prepareStatement(sql)) {
            bindArgs(ps, args);
            List<TaskMsg> messages = new ArrayList<>();
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    messages.add(readJson(rs.getString(1), TaskMsg.class));
                }
            }
            return messages;
        } catch (Exception e) {
            throw new IllegalStateException("Failed to query task messages", e);
        }
    }

    private List<TaskMsgAttempt> queryAttempts(String sql, String... args) {
        try (var conn = connection(); var ps = conn.prepareStatement(sql)) {
            bindArgs(ps, args);
            List<TaskMsgAttempt> attempts = new ArrayList<>();
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    attempts.add(readJson(rs.getString(1), TaskMsgAttempt.class));
                }
            }
            return attempts;
        } catch (Exception e) {
            throw new IllegalStateException("Failed to query task-message attempts", e);
        }
    }

    private TaskMessageAttemptStats attemptStats(String whereClause, String... args) {
        try (var conn = connection(); var ps = conn.prepareStatement("""
                SELECT COUNT(*) total_count,
                       SUM(CASE WHEN active_state = TRUE THEN 1 ELSE 0 END) active_count,
                       SUM(CASE WHEN status = 'RUNNING' THEN 1 ELSE 0 END) running_count,
                       SUM(CASE WHEN status = 'FAILED' THEN 1 ELSE 0 END) failed_count,
                       SUM(CASE WHEN status = 'EXPIRED' THEN 1 ELSE 0 END) expired_count
                FROM xa_task_msg_attempt
                """ + whereClause)) {
            bindArgs(ps, args);
            try (ResultSet rs = ps.executeQuery()) {
                if (!rs.next()) {
                    return new TaskMessageAttemptStats(0, 0, 0, 0, 0);
                }
                return new TaskMessageAttemptStats(rs.getLong(1), rs.getLong(2), rs.getLong(3), rs.getLong(4), rs.getLong(5));
            }
        } catch (Exception e) {
            throw new IllegalStateException("Failed to get task-message attempt stats", e);
        }
    }

    private long queryLong(String sql, String arg) {
        try (var conn = connection(); var ps = conn.prepareStatement(sql)) {
            ps.setString(1, arg);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? rs.getLong(1) : 0L;
            }
        } catch (Exception e) {
            throw new IllegalStateException("Failed to query count", e);
        }
    }

    private void bindTask(PreparedStatement ps, Task task) throws Exception {
        ps.setString(1, task.getTid());
        ps.setString(2, task.getStatus() == null ? null : task.getStatus().name());
        ps.setString(3, task.getProject());
        ps.setBoolean(4, task.isSchedulable());
        setTimestamp(ps, 5, maxRuntimeDeadline(task));
        ps.setString(6, json(task));
    }

    private void bindTaskMessage(PreparedStatement ps, String taskId, TaskMsg taskMsg) throws Exception {
        TaskMsgStatus status = taskMsg.getStatus();
        ps.setString(1, taskId);
        ps.setString(2, taskMsg.getMessageId());
        ps.setString(3, status == null ? null : status.name());
        ps.setBoolean(4, status == null || status.isFinal());
        ps.setString(5, json(taskMsg));
    }

    private void bindAttempt(PreparedStatement ps, String taskId, String messageId, TaskMsgAttempt attempt) throws Exception {
        TaskMsgAttemptStatus status = attempt.getStatus();
        ps.setString(1, taskId);
        ps.setString(2, messageId);
        ps.setString(3, attempt.getAttemptId());
        ps.setString(4, status == null ? null : status.name());
        ps.setBoolean(5, status != null && status.isActive());
        ps.setString(6, json(attempt));
    }

    private void bindArgs(PreparedStatement ps, String... args) throws Exception {
        for (int i = 0; i < args.length; i++) {
            ps.setString(i + 1, args[i]);
        }
    }

    private int executeUpdate(java.sql.Connection conn, String sql, String arg) throws Exception {
        try (var ps = conn.prepareStatement(sql)) {
            ps.setString(1, arg);
            return ps.executeUpdate();
        }
    }

    private void setTimestamp(PreparedStatement ps, int index, LocalDateTime value) throws Exception {
        if (value == null) {
            ps.setTimestamp(index, null);
        } else {
            ps.setTimestamp(index, Timestamp.valueOf(value));
        }
    }

    private LocalDateTime maxRuntimeDeadline(Task task) {
        if (task == null || task.getStatus() == null || task.getStatus().isFinal()
                || task.getMaxRuntimeSeconds() <= 0 || task.getStartTime() == null) {
            return null;
        }
        return task.getStartTime().plusSeconds(task.getMaxRuntimeSeconds());
    }
}
