package com.xa.mass.engine.model;

import java.util.List;

/**
 * Engine-owned append command result. Message ids are generated by the append
 * owner and returned so result callbacks can correlate accepted items.
 */
public record TaskAppendOutcome(
        String taskId,
        boolean accepted,
        int acceptedCount,
        List<String> messageIds,
        String reasonCode,
        String message
) {

    public TaskAppendOutcome {
        acceptedCount = accepted ? Math.max(0, acceptedCount) : 0;
        messageIds = messageIds == null ? List.of() : List.copyOf(messageIds);
        reasonCode = normalize(reasonCode);
        message = normalize(message);
    }

    public static TaskAppendOutcome accepted(String taskId, int acceptedCount, List<String> messageIds) {
        return new TaskAppendOutcome(
                taskId,
                true,
                acceptedCount,
                messageIds,
                "ITEMS_ACCEPTED",
                "Task items accepted"
        );
    }

    public static TaskAppendOutcome rejected(String taskId, String reasonCode, String message) {
        return new TaskAppendOutcome(taskId, false, 0, List.of(), reasonCode, message);
    }

    private static String normalize(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }
        return value.trim();
    }
}
