<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xa.mass</groupId>
        <artifactId>xa_mass_platform</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>xa-mass-engine-starter</artifactId>
    <packaging>jar</packaging>
    <name>xa-mass-engine-starter</name>

    <dependencies>
        <dependency>
            <groupId>com.xa.mass</groupId>
            <artifactId>xa-mass-engine</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.xa.mass</groupId>
            <artifactId>xa-mass-worker-runtime</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.xa.mass</groupId>
            <artifactId>mass-runtime-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.xa.mass</groupId>
            <artifactId>mass-runtime-memory</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.xa.mass</groupId>
            <artifactId>mass-storage-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.xa.mass</groupId>
            <artifactId>mass-storage-memory</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.xa.mass</groupId>
            <artifactId>mass-trace-sink</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.xa.mass</groupId>
            <artifactId>xa-mass-embedded-sdk-api</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
