plugins {
    id 'java-library'
}

base {
    archivesName.set('xa-mass-worker-delivery-contract')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.named('compileJava', JavaCompile) {
    options.release = 11
}

dependencies {
    implementation 'com.google.code.gson:gson:2.14.0'

    testImplementation platform('org.junit:junit-bom:5.12.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('compileTestJava', JavaCompile) {
    options.release = 21
}

tasks.named('test') {
    useJUnitPlatform()
}
