spring.application.name=mass_server
server.port=8081
mock.client.count=5
mock.client.uri=ws://localhost:8088/ws
mock.task.interval=30000

websocket.server.port=8088
websocket.server.path=/ws

spring.profiles.active=prod
# Spring Redis
spring.redis.host=localhost
spring.redis.port=6379
# spring.redis.password=your_password_if_any
spring.redis.database=0

# Mass Queue Redis Stream Config
mass.queue.input.stream-key=mass_server_input_stream
mass.queue.input.group-name=mass_server_input_group
mass.queue.input.consumer-name=mass_server_input_consumer_instance_1 # ??????????????????????????????????

mass.queue.output.stream-key=mass_server_output_stream
mass.queue.output.group-name=mass_server_output_group
mass.queue.output.consumer-name=mass_server_output_consumer_instance_1


