<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xa.mass</groupId>
        <artifactId>xa_mass_platform</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>
    <artifactId>mass-storage-jdbc</artifactId>
    <packaging>jar</packaging>
    <name>mass-storage-jdbc</name>

    <dependencies>
        <dependency>
            <groupId>com.xa.mass</groupId>
            <artifactId>xa-mass-engine</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.xa.mass</groupId>
            <artifactId>mass-storage-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.xa.mass</groupId>
            <artifactId>mass-storage-memory</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.xa.mass</groupId>
            <artifactId>xa-mass-sdk-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.opentable.components</groupId>
            <artifactId>otj-pg-embedded</artifactId>
            <version>1.0.3</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
