plugins {
    id 'com.android.library'
}

base {
    archivesName.set('xa-mass-android-client')
}

android {
    namespace = 'com.xa.mass.transport.android'
    compileSdk = 36

    defaultConfig {
        minSdk = 24
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
}

dependencies {
    api project(':transport:core')
    implementation 'com.squareup.okhttp3:okhttp:5.3.0'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.16.1'
    testImplementation 'com.squareup.okhttp3:mockwebserver3:5.3.0'
}
