plugins {
    id 'com.android.application'
}

base {
    archivesName.set('xa-mass-android-worker-demo')
}

android {
    namespace = 'com.xa.mass.android.workerdemo'
    compileSdk = 36

    defaultConfig {
        applicationId = 'com.xa.mass.integration.androidworker'
        minSdk = 24
        targetSdk = 36
        versionCode = 1
        versionName = '0.1.0'
    }

    buildTypes {
        lab1 {
            initWith debug
            applicationIdSuffix = '.lab1'
            matchingFallbacks = ['debug']
        }
        lab2 {
            initWith debug
            applicationIdSuffix = '.lab2'
            matchingFallbacks = ['debug']
        }
        lab3 {
            initWith debug
            applicationIdSuffix = '.lab3'
            matchingFallbacks = ['debug']
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
}

dependencies {
    implementation project(':transport:android-worker')
    implementation project(':xa-android:capabilities')
    implementation project(':xa-android:capability-http')
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.16.1'
    testImplementation 'com.squareup.okhttp3:mockwebserver3:5.3.0'
}
