plugins {
    id 'com.android.library'
    id 'maven-publish'
}

base {
    archivesName.set('xa-mass-android-worker')
}

android {
    namespace = 'com.xa.mass.worker.android'
    compileSdk = 36

    defaultConfig {
        minSdk = 24
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
}

afterEvaluate {
    publishing {
        publications {
            workerSdk(MavenPublication) {
                from components.release
                artifactId = 'xa-mass-android-worker'
            }
        }
        repositories {
            maven {
                name = 'workerSdk'
                url = rootProject.layout.projectDirectory.dir(
                        'distribution/worker-sdk/build/repository'
                )
            }
        }
    }
}

dependencies {
    api project(':transport:worker-core')
    implementation 'com.squareup.okhttp3:okhttp:5.3.0'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.16.1'
    testImplementation 'com.squareup.okhttp3:mockwebserver3:5.3.0'
}
