import type { AppRouteRecordRaw } from '@/router/types'

export const utilityRoutes: AppRouteRecordRaw[] = [
    {
        path: 'login',
        name: 'login',
        component: () => import('@/pages/app/LoginPage.vue'),
        meta: {
            shell: 'public',
            navGroup: 'public',
            title: 'Operator Login',
            icon: 'Lock',
            order: 10,
            hidden: true,
            keepAlive: false,
            requiresAuth: false,
            permissions: [],
            menuVisible: false,
        },
    },
    {
        path: 'api-key-viewer',
        name: 'api-key-viewer',
        component: () => import('@/pages/api-key-viewer/ApiKeyViewerPage.vue'),
        meta: {
            shell: 'api-key-viewer',
            navGroup: 'viewer',
            title: 'API-Key Viewer',
            icon: 'Tickets',
            order: 56,
            hidden: false,
            keepAlive: true,
            requiresAuth: false,
            permissions: [],
            menuVisible: true,
        },
    },
    {
        path: 'forbidden',
        name: 'forbidden',
        component: () => import('@/pages/app/ForbiddenPage.vue'),
        meta: {
            shell: 'public',
            navGroup: 'public',
            title: 'Forbidden',
            icon: 'WarningFilled',
            order: 90,
            hidden: true,
            keepAlive: false,
            requiresAuth: false,
            permissions: [],
            menuVisible: false,
        },
    },
    {
        path: ':pathMatch(.*)*',
        name: 'not-found',
        component: () => import('@/pages/app/NotFoundPage.vue'),
        meta: {
            shell: 'public',
            navGroup: 'public',
            title: 'Not Found',
            icon: 'Warning',
            order: 99,
            hidden: true,
            keepAlive: false,
            requiresAuth: false,
            permissions: [],
            menuVisible: false,
        },
    },
]
